

Animal.destroy_all


animal1 = Animal.create(group:"Dog", species:"Dog", breeds:"Golden Poodle", color:"white", age:"Young", gender:"Male", size:"Medium", environment:"good with kids", tags:"upbeat", name:"Tommy", description:"Great dog for a family", photos:"https://images.squarespace-cdn.com/content/v1/56167d8fe4b02dbafff2d5c9/1533871050605-ZBURRESUZJMN4J4RNDSW/ke17ZwdGBToddI8pDm48kOggE0Ch6pMGalwtLMqzsSB7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1Ufo5RWkg_J4of0jUNHaDHx6pZKBvpVYzidBWCapg0tuoMuEaB2HPGSYDV-11UTcW2g/image-asset.jpeg", status:"available", location: "Virginia")
animal2= Animal.create(group:"Dog", species:"Dog", breeds:"Golden Retriver", color:"Golden", age:"Young", gender:"Male", size:"Medium", environment:"Amazing with kids", tags:"Energetic", name:"Buddy", description:"Energetic Puppy to have that needs some space out doors", photos:"http://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max", status:"available", location:"Maryland")
animal3 = Animal.create(group:"Dog", species:"Dog", breeds:"West Highland White Terrier", color:"white", age:"Young", gender:"Male", size:"Medium", environment:"good with kids", tags:"barks", name:"Tim", description:"Awesome dog to have, enjoys long walks and tennis balls", photos:"https://vetstreet-brightspot.s3.amazonaws.com/9d/b6/4594ad684c7bae3bebd2a5a0f9f5/white-dog-thinkstockphotos-177514586-590sm6415.jpg", status:"available", location:"Florida")
animal4 = Animal.create(group:"Cat", species:"Cat", breeds:"Turkis Angora", color:"White", age:"Old", gender:"Female", size:"Medium", environment:"good with kids", tags:"lazy", name:"Louie", description:"Really fun cat to have, loves to jump off shelfs and tables", photos:"https://www.thesprucepets.com/thmb/gj5LXtuEXDbrd3MMxCFVbEraDnU=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/33351631_260594934684461_1144904437047754752_n-5b17d77604d1cf0037f3ea5a.jpg", status:"available", location:"California")
animal5 = Animal.create(group:"Cat", species:"Cat", breeds:"house", color:"Black and White stripes", age:"adult", gender:"Male", size:"Large", environment:"bad with kids", tags:"lazy", name:"Trott", description:"really fun cat to have", photos:"https://upload.wikimedia.org/wikipedia/commons/3/38/Adorable-animal-cat-20787.jpg", status:"available", location:"Virginia")
animal6 = Animal.create(group:"Cat", species:"Cat", breeds:"house", color:"white", age:"Young", gender:"Male", size:"Medium", environment:"bad with kids", tags:"lazy", name:"Tarry", description:"really fun dog to have", photos:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cute-cat-photos-1593441022.jpg?crop=1.00xw:0.749xh;0,0.154xh&resize=980:*", status:"available", location:"Texas")
animal7 = Animal.create(group:"Turtle", species:"Turtle", breeds:"Green Turtle", color:'Green', age:"old", gender:"Male", size:"Small", environment:"Great for kids", tags:"lazy", name:"Crush", description:"Awesome Turtle that does nothing but love you", photos:"https://www.petmd.com/sites/default/files/childs-hands-holding-turtle_147984695_0.jpg", status:"available", location:"Virginia")
animal8 = Animal.create(group:"Bird", species:"Bird", breeds:"Pacific Parrotlet", color:"Blue", age:"Young", gender:"Male", size:"Medium", environment:"Excellent with kids, might even teach them new words", tags:"Moring bird", name:"Zazu", description:"Funny bird to have that will repeat your lingo", photos:"https://www.thesprucepets.com/thmb/YUaTdtWAbDSVDZsmsydsNdOM8qQ=/2124x1195/smart/filters:no_upscale()/GettyImages-655307584-5c76f13546e0fb0001edc770.jpg", status:"available", location:"Florida")
animal9 = Animal.create(group:"Bird", species:"Bird", breeds:"Fischer's LoverBird", color:"Orange and Green", age:"Young", gender:"Female", size:"Large", environment:"Great with kids", tags:"Cool", name:"Marry", description:"Awesome Bird to have in the house", photos:"https://www.cdc.gov/healthypets/images/pets/birds-pet-parrot.jpg", status:"available", location:"Texas")
animal10 = Animal.create(group:"Fish", species:"Fish", breeds:"Clown", color:"White and Orange", age:"one Young, one old", gender:"Male", size:"Medium", environment:"Great fish to have in your fish tank", tags:"fun", name:"Nemo and Marlin", description:"Two for one deal on Clown Fish", photos:"https://i.pinimg.com/originals/3c/56/99/3c5699aa384fcf34e27b118f4311cd89.jpg", status:"available", location:"Florida")
animal11 = Animal.create(group:"Dog", species:"Dog", breeds:"French Bulldog", color:"Black", age:"Medium", gender:"Female", size:"Small", environment:"Great with kids", tags:"Energetic", name:"Chance", description:"Very Playful bulldog", photos:"https://dogtime.com/assets/uploads/gallery/french-bulldog-dog-breed-pictures/1-puppy.jpg", status:"available", location:"Texas")
animal12= Animal.create(group:"Cat", species:"Cat", breeds:"Bengal", color:"Black and White stripes", age:"Young", gender:"Male", size:"Small", environment:"bad with kids", tags:"Playful", name:"Tiger", description:"Playful Cat with a love for yarn", photos:"https://t4.ftcdn.net/jpg/02/18/17/09/360_F_218170901_GsnXzeZfYJ27kZUc8O56CFmvOzthCOrJ.jpg", status:"available", location:"Virginia")
animal13= Animal.create(group:"Fish", species:"Fish", breeds:"Betta", color:"Colorful", age:"Young", gender:"Male", size:"Medium", environment:"Good with kids", tags:"lazy", name:"Billy", description:"Very Colorful fish, friendly with other fish", photos:"https://ornamentalfish.org/wp-content/uploads/betta-fish.jpg", status:"available", location:"Florida")
animal14= Animal.create(group:"Turtle", species:"Tutle", breeds:"Three-Toed Box Turtle", color:"white", age:"Young", gender:"Male", size:"Medium", environment:"Good with kids", tags:"lazy", name:"Bulbasaur", description:"Laid back turtle that enjoys eating zucchinies everyday ", photos:"https://i.pinimg.com/originals/cd/5b/e9/cd5be92c353be4ac383d4644ffeccb64.jpg", status:"available", location:"Maryland")






